/**
 * Types and service definitions for boot preflight inspection and self-healing.
 * @module @deepseek-ai/dsh-boot-self-heal/types
 */

import '@deepseek-ai/cordis'

/** Failure codes detected by boot inspection. */
export type BootIssueCode =
  | 'MISSING_CLIENT_RECORD'
  | 'STALE_CLIENT_RECORD'
  | 'CORRUPT_CLIENT_RECORD'
  | 'MISSING_CLIENT_BUNDLE'
  | 'LOCK_FILE_CONFLICT'

/** Remediation actions available to restore boot integrity. */
export type RemediationAction =
  | 'BUILD_CLIENT'
  | 'REBUILD_WORKSPACE'
  | 'CLEAN_TEMP_LOCKS'
  | 'SWITCH_RESCUE_PROFILE'

/** One detected boot integrity issue. */
export interface BootHealthIssue {
  /** Discriminant code identifying the issue type. */
  readonly code: BootIssueCode
  /** Human-readable diagnosis explaining why the issue prevents boot. */
  readonly message: string
  /** Specific package, bundle, or path causing the failure, if known. */
  readonly target?: string
  /** Whether automatic remediation can be attempted without manual user intervention. */
  readonly autoFixable: boolean
  /** The recovery action recommended or executed. */
  readonly remediationAction: RemediationAction
}

/** Result of an individual remediation attempt. */
export interface RemediationAttempt {
  /** The issue targeted by this remediation. */
  readonly issue: BootHealthIssue
  /** Whether the remediation action succeeded. */
  readonly success: boolean
  /** Output or diagnostic details from the remediation execution. */
  readonly details: string
}

/** Complete report generated by the boot health inspection and self-healing service. */
export interface BootSelfHealReport {
  /** True when no issues exist or all detected issues were successfully repaired. */
  readonly healthy: boolean
  /** All detected integrity issues during inspection. */
  readonly issues: readonly BootHealthIssue[]
  /** Detailed log of all attempted remediation operations. */
  readonly attemptedRemediations: readonly RemediationAttempt[]
  /** Profile name if fallback to rescue mode occurred. */
  readonly fallbackProfileUsed?: string
}

/** Service definition for preflight boot inspection and autonomous environment repair. */
export interface BootSelfHealService {
  /**
   * Inspect the current repository and boot environment for missing client
   * bundles, missing or stale build records, and known filesystem locks.
   * @param rootDir - repository root directory.
   * @returns report describing whether the environment is healthy and any detected issues.
   */
  inspectBootEnvironment(rootDir: string): Promise<BootSelfHealReport>

  /**
   * Execute auto-remediation routines for detected fixable issues.
   * @param rootDir - repository root directory.
   * @param issues - list of issues to remediate.
   * @returns final report after remediation attempts.
   */
  remediate(rootDir: string, issues: readonly BootHealthIssue[]): Promise<BootSelfHealReport>
}

declare module '@deepseek-ai/cordis' {
  interface Context {
    /** Boot health inspection and self-healing service. */
    bootSelfHeal?: BootSelfHealService
  }
}
